### ISSUE TITLE
Please clarify that the script is Windows-only

### ISSUE THREAD

**Issue by 07416** [FailSpy/humble-steam-key-redeemer#28]
'Batchfile' is mentioned under languages, but I still managed to clone to repository and install the requirements on Linux. Also step-by-step instructions would likely prevent similar cases.

**Comment by FailSpy** [comment]
There is no reason to clarify this because the script is designed to be platform-agnostic thanks to Python compatibilities. It works for Windows, Linux (which is what I developed it on), and I'd imagine Mac OS.

The batchfile there is purely for Windows users convenience as early on particularly Windows users were confused how to run it, and if I have the ability to avoid them navigating a terminal, why not spare them? I could include a step-by-step instruction though for other platforms.

If the script is not working, it's because it doesn't work right now for other reasons: which is the CloudFlare bot protection that I've not had time to resolve.
