### ISSUE TITLE
Question: Redeeming owned keys

### ISSUE THREAD

**Issue by hydroculator** [FailSpy/humble-steam-key-redeemer#37]
The description says that the program pulls all keys from Humble, *then* checks to see what the user already owns on Steam.
Can it not check first before pulling codes that can't be activated?    
I like to keep my duplicates in Humble for later, in case I find someone who wants a key. If they're *all* redeemed at once, that becomes difficult.   
Thanks

**Comment by FailSpy** [comment]
Good point on the wording, should probably clarify that.

The auto-redeem functionality only touches keys that are one, Steam keys, and two, will only 'reveal' a key on Humble if it's certain you don't already own it. 
Additionally, for added safety it only reveals keys on Humble as it goes to redeem them on Steam.

I can't really guarantee that it does this owned-games-aversion perfectly, but I did try to bias the code to prefer NOT revealing keys under any concern it might already be owned, rather than to be greedy -- for exactly the reason you stated.

It's worth noting that if you use export mode and select the option to 'reveal keys' at the start, then that _will_ redeem & export _every_ key.

**Comment by FailSpy** [comment]
I've gone ahead and clarified the README as it was overdue for an update. Thanks! Let me know if you run into any issues.

**Comment by hydroculator** [comment]
Thanks very much for the clarification and the update! I'll be trying this out very soon.

**Comment by MDKAOD** [comment]
@hydroculator Consider the reason I'm using this app. I have tried to redeem a few old keys lately and Humble doesn't have them any longer and keys are repopulated via publisher, not Humble. There's no guarantee I'll ever get these keys back.
